# -*- coding: utf-8 -*-
"""PM_Copilot_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BRaGhlDcfI1iTlVA_uniCJeX1WcdpnDZ

# 🧠 PM Copilot — Multi-Agent Product Management Assistant
### IE5374 Applied Generative AI · Dr. Dehghani · Spring 2026

---

## Overview

**PM Copilot** transforms a plain-language product idea into a complete PM deliverable suite:

| Output | Agent | LLM | Cost |
|--------|-------|-----|------|
| 📄 Product Requirements Document | PRD Agent | **GPT-4o** | Paid |
| 📊 Market Sizing & Competitive Analysis | Market Agent | **Gemini 1.5 Flash** | Free tier |
| 🗂 User Stories with Acceptance Criteria | Stories Agent | **Groq / Llama-3.3-70b** | Free |
| ⚠️ Risk Assessment Register | Risk Agent | **Groq / Llama-3.3-70b** | Free |

**Orchestration:** LangChain routes each task to the most capable LLM by task type.

---

### System Architecture

```
User Input (Product Idea)
        │
        ▼
┌─────────────────────────────┐
│   LangChain Orchestrator    │  ← Routes tasks by type
│   (Keyword-based routing)   │
└──────┬──────────┬───────────┘
       │          │          │
       ▼          ▼          ▼
  ┌────────┐ ┌─────────┐ ┌──────────────┐
  │ GPT-4o │ │  Groq   │ │Gemini Flash  │
  │  PRD   │ │ Llama-3 │ │   Market     │
  │        │ │Stories  │ │   Research   │
  │        │ │ Risk    │ │              │
  └────────┘ └─────────┘ └──────────────┘
       │          │          │
       └──────────┴──────────┘
                  │
                  ▼
       ┌──────────────────┐
       │ Assembled Output │
       │  (Streamlit UI)  │
       └──────────────────┘
```

## Section 1: Install Dependencies

We use three LLM providers:
- **OpenAI** (GPT-4o) — paid, for complex PRD generation
- **Groq** (Llama-3.3-70b) — **completely free**, replaces Anthropic for stories and risk
- **Google Gemini Flash** — free tier, for market research

> **Get your free Groq API key:** https://console.groq.com → Sign up → API Keys → No credit card needed
"""

# Install all required packages
!pip install -q langchain langchain-core langchain-openai langchain-groq langchain-google-genai
!pip install -q openai groq google-generativeai nest_asyncio streamlit python-dotenv
print("✅ All packages installed successfully")

# Core imports — using langchain_core.messages (correct for modern LangChain)
import os
import time
import json
from pathlib import Path

# IMPORTANT: import from langchain_core, not langchain.schema
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from langchain_groq import ChatGroq
from langchain_google_genai import ChatGoogleGenerativeAI

# Detect Colab environment
try:
    from google.colab import userdata
    COLAB = True
except ImportError:
    COLAB = False

print(f"✅ All imports successful")
print(f"   Running in Colab: {COLAB}")
print(f"   Using: langchain_core.messages (modern LangChain) ✓")

"""## Section 2: API Key Configuration

### Setup Instructions
1. Click the 🔑 **Secrets** icon in the left Colab sidebar
2. Add these three secrets and toggle **Notebook access ON**:

| Secret Name | Where to get it | Cost |
|-------------|-----------------|------|
| `OPENAI_API_KEY` | https://platform.openai.com/api-keys | Paid |
| `GROQ_API_KEY` | https://console.groq.com | **Free** |
| `GOOGLE_API_KEY` | https://aistudio.google.com/app/apikey | **Free tier** |

"""

def load_api_keys():
    """Load API keys from Colab Secrets or environment variables."""
    if COLAB:
        os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")
        os.environ["GROQ_API_KEY"]   = userdata.get("GROQ_API_KEY")
        os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")
        print("✅ Keys loaded from Colab Secrets")
    else:
        os.environ.setdefault("OPENAI_API_KEY", "")
        os.environ.setdefault("GROQ_API_KEY", "")
        os.environ.setdefault("GOOGLE_API_KEY", "")
        print("✅ Keys loaded from environment")

    missing = [k for k in ["OPENAI_API_KEY","GROQ_API_KEY","GOOGLE_API_KEY"]
               if not os.getenv(k) or os.getenv(k).endswith("...")]
    if missing:
        print(f"⚠️  Missing or placeholder keys: {missing}")
    else:
        print("✅ All three API keys configured")

load_api_keys()

"""## Section 3: LLM Client Initialization

| Client | Model | Assigned Task | Why |
|--------|-------|---------------|-----|
| `gpt` | gpt-4o | PRD generation | Best at long structured document generation |
| `groq_llm` | llama-3.3-70b-versatile | Stories + Risk | Free, fast, great template-following |
| `gemini` | gemini-1.5-flash | Market research | Free tier, strong at research summaries |

"""

def init_llms():
    """
    Initialize all three LLM clients.

    Temperature guide:
      0.4 → slight creativity for PRD
      0.3 → balanced for stories (structured but not robotic)
      0.2 → low for market data (factual and grounded)
    """
    gpt = ChatOpenAI(
        model="gpt-4o",
        temperature=0.4,
        api_key=os.getenv("OPENAI_API_KEY"),
    )
    print("✅ GPT-4o initialized  (OpenAI — paid)")

    # Groq: completely FREE, Llama-3.3-70b quality rivals Claude 3
    groq_llm = ChatGroq(
        model="llama-3.3-70b-versatile",
        temperature=0.3,
        api_key=os.getenv("GROQ_API_KEY"),
    )
    print("✅ Llama-3.3-70b initialized  (Groq — FREE)")

    # Gemini quota exhausted — using Groq for market research too (FREE)
    gemini = ChatGroq(
        model="llama-3.3-70b-versatile",
        temperature=0.2,
        api_key=os.getenv("GROQ_API_KEY"),
    )
    print("✅ Market agent initialized  (Groq — FREE)")

    return gpt, groq_llm, gemini

gpt, groq_llm, gemini = init_llms()

"""## Section 4: Agent Definitions

Each agent is an independent function with its own system prompt, LLM binding, and output contract.

"""

# ─────────────────────────────────────────────
# AGENT 1: PRD Agent  →  GPT-4o
# ─────────────────────────────────────────────
def prd_agent(product_idea: str, context: str = "") -> str:
    """
    Generates a Product Requirements Document using GPT-4o.

    Why GPT-4o: Superior at multi-section structured document generation
    and handles ambiguous product descriptions through reasoning.
    """
    system = """You are a senior Product Manager. Write a comprehensive PRD with:
## Overview
## Problem Statement
## Proposed Solution
## Target Users
## Functional Requirements
## Non-Functional Requirements
## Success Metrics
## Out of Scope
Be specific. Bullet points. Every requirement must be testable."""

    return gpt.invoke([
        SystemMessage(content=system),
        HumanMessage(content=f"Product Idea: {product_idea}\n\nContext: {context}\n\nGenerate a complete PRD."),
    ]).content

print("✅ PRD Agent  →  GPT-4o")

# ─────────────────────────────────────────────
# AGENT 2: Market Research Agent  →  Gemini Flash
# ─────────────────────────────────────────────
def market_agent(product_idea: str, context: str = "") -> str:
    """
    Generates market sizing and competitive analysis using Gemini Flash.

    Why Gemini Flash: Fast (~2-4s), strong at research tasks, free tier.
    """
    system = """You are a market research analyst. Provide:
## Market Sizing
- TAM with assumptions, SAM, SOM (3-year target)
## Competitive Landscape
3-5 real competitors with strengths/weaknesses.
## Key Market Trends
3-4 relevant trends.
## Go-to-Market Recommendation
1-2 paragraphs with real numbers."""

    return gemini.invoke([
        SystemMessage(content=system),
        HumanMessage(content=f"Product Idea: {product_idea}\n\nContext: {context}\n\nProvide market analysis."),
    ]).content

print("✅ Market Research Agent  →  Gemini Flash (free)")

# ─────────────────────────────────────────────
# AGENT 3: User Stories Agent  →  Groq / Llama-3.3
# ─────────────────────────────────────────────
def stories_agent(product_idea: str, prd_content: str = "") -> str:
    """
    Generates user stories with acceptance criteria using Groq/Llama-3.3.

    Why Groq/Llama-3.3: Completely FREE, excellent at strict template-following,
    fast inference on Groq hardware. Replaces paid Claude 3 Sonnet.
    """
    system = """You are an Agile product manager. Generate user stories in EXACT format:

### Story [N]: [Title]
**As a** [user type], **I want** [goal], **so that** [benefit].

**Acceptance Criteria:**
- [ ] Criterion 1
- [ ] Criterion 2
- [ ] Criterion 3

**Story Points:** [1/2/3/5/8]
**Priority:** [High/Medium/Low]

Generate 8-12 stories grouped into Epics.
Cover core features, edge cases, and admin needs."""

    return groq_llm.invoke([
        SystemMessage(content=system),
        HumanMessage(content=f"Product: {product_idea}\n\nPRD:\n{prd_content[:1500]}\n\nGenerate user stories."),
    ]).content

print("✅ User Stories Agent  →  Groq / Llama-3.3 (free)")

# ─────────────────────────────────────────────
# AGENT 4: Risk Assessment Agent  →  Groq / Llama-3.3
# ─────────────────────────────────────────────
def risk_agent(product_idea: str, market_content: str = "") -> str:
    """
    Generates a risk register using Groq/Llama-3.3.

    Why Groq/Llama-3.3: Free, excellent at structured tabular output,
    produces nuanced severity/likelihood analysis.
    """
    system = """You are a risk management consultant. Generate:

## Technical Risks
| Risk | Severity | Likelihood | Mitigation |
|------|----------|------------|------------|

## Market Risks
| Risk | Severity | Likelihood | Mitigation |
|------|----------|------------|------------|

## Execution Risks
| Risk | Severity | Likelihood | Mitigation |
|------|----------|------------|------------|

## Top 3 Priority Risks
With specific action items and owners.
Use High/Medium/Low. Be product-specific."""

    return groq_llm.invoke([
        SystemMessage(content=system),
        HumanMessage(content=f"Product: {product_idea}\n\nMarket Context:\n{market_content[:1000]}\n\nGenerate risk assessment."),
    ]).content

print("✅ Risk Assessment Agent  →  Groq / Llama-3.3 (free)")

"""## Section 5: Orchestrator — Routing Logic

Routes follow-up questions to the right agent based on keyword classification.

```
"story/epic/backlog"        →  Groq/Llama (Stories)
"market/competitor/pricing" →  Gemini (Market)
"risk/threat/mitigation"    →  Groq/Llama (Risk)
everything else             →  GPT-4o
```

"""

def route_refinement(question: str, product_idea: str, outputs: dict, history: list) -> tuple:
    """
    Routes a follow-up question to the most appropriate agent.
    Maintains conversation context across turns.
    """
    q = question.lower()

    if any(k in q for k in ["story","stories","epic","sprint","backlog","acceptance"]):
        print("→ Groq / Llama-3.3 (Stories domain)")
        system = "You are an Agile PM. Refine or expand user stories using the product context."
        llm, agent = groq_llm, "Groq / Llama-3.3"
    elif any(k in q for k in ["market","competitor","tam","sam","revenue","pricing","gtm"]):
        print("→ Gemini Flash (Market domain)")
        system = "You are a market research analyst. Answer using the existing product context."
        llm, agent = gemini, "Gemini Flash"
    elif any(k in q for k in ["risk","threat","mitigation","challenge","concern"]):
        print("→ Groq / Llama-3.3 (Risk domain)")
        system = "You are a risk management consultant. Answer using the product context."
        llm, agent = groq_llm, "Groq / Llama-3.3"
    else:
        print("→ GPT-4o (General reasoning)")
        system = "You are a senior PM. Answer using all available context."
        llm, agent = gpt, "GPT-4o"

    context = f"Product: {product_idea}\n\n"
    if outputs.get("prd"):    context += f"PRD excerpt:\n{outputs['prd'][:600]}\n\n"
    if outputs.get("market"): context += f"Market excerpt:\n{outputs['market'][:400]}\n\n"
    for msg in history[-4:]:
        context += f"{msg['role'].title()}: {msg['content'][:200]}\n"

    response = llm.invoke([
        SystemMessage(content=system),
        HumanMessage(content=f"{context}\nQuestion: {question}"),
    ])
    return response.content, agent

print("✅ Orchestrator routing function defined")

"""## Section 6: Main Pipeline

Runs all four agents sequentially. Downstream agents use upstream outputs as context.

"""

def generate_pm_suite(product_idea: str, verbose: bool = True) -> dict:
    """
    Main orchestration pipeline — runs all four agents in sequence.
    Sequential ensures downstream agents can use upstream outputs as context.
    """
    outputs = {}
    total_start = time.time()

    if verbose:
        print(f"{'='*60}")
        print(f"🚀 PM Copilot — Generating Full PM Suite")
        print(f"   Product: {product_idea[:70]}...")
        print(f"{'='*60}\n")

    if verbose: print("🟦 [1/4] GPT-4o → Generating PRD...")
    t = time.time()
    outputs["prd"] = prd_agent(product_idea)
    if verbose: print(f"   ✅ Done ({time.time()-t:.1f}s)\n")

    if verbose: print("🟩 [2/4] Gemini Flash → Researching market...")
    t = time.time()
    outputs["market"] = market_agent(product_idea)
    if verbose: print(f"   ✅ Done ({time.time()-t:.1f}s)\n")

    if verbose: print("🟪 [3/4] Groq/Llama → Writing user stories...")
    t = time.time()
    outputs["stories"] = stories_agent(product_idea, outputs["prd"])
    if verbose: print(f"   ✅ Done ({time.time()-t:.1f}s)\n")

    if verbose: print("🟪 [4/4] Groq/Llama → Assessing risks...")
    t = time.time()
    outputs["risks"] = risk_agent(product_idea, outputs["market"])
    if verbose: print(f"   ✅ Done ({time.time()-t:.1f}s)\n")

    if verbose:
        print(f"✅ All 4 outputs in {time.time()-total_start:.1f}s")
        print(f"   Cost: GPT-4o (PRD only) + Groq FREE + Gemini FREE")

    return outputs

print("✅ Pipeline defined")

"""## Section 7: Run Demo

▶️ Makes real API calls — runtime ~30–90 seconds.

"""

PRODUCT_IDEA = """
A fitness tracking app for remote workers that gamifies daily movement
with team challenges, streak tracking, and Slack integration.
""".strip()

outputs = generate_pm_suite(PRODUCT_IDEA)

from IPython.display import Markdown, display
print("📄 PRD (GPT-4o)"); display(Markdown(outputs["prd"]))

print("📊 MARKET ANALYSIS (Gemini Flash)"); display(Markdown(outputs["market"]))

print("🗂 USER STORIES (Groq / Llama-3.3)"); display(Markdown(outputs["stories"]))

print("⚠️ RISK ASSESSMENT (Groq / Llama-3.3)"); display(Markdown(outputs["risks"]))

"""## Section 8: Parallel Execution with asyncio

Runs PRD + Market simultaneously (Round 1), then Stories + Risk simultaneously (Round 2). ~2x faster than sequential.

"""

import asyncio
import nest_asyncio
nest_asyncio.apply()  # Required for Colab

async def generate_parallel(product_idea: str) -> dict:
    """Parallel pipeline — cuts runtime roughly in half."""
    print(f"⚡ Parallel pipeline starting...\n")
    start = time.time()
    loop = asyncio.get_event_loop()

    # Round 1: PRD + Market (no dependencies between them)
    print("Round 1: GPT-4o + Gemini running simultaneously...")
    prd_result, market_result = await asyncio.gather(
        loop.run_in_executor(None, prd_agent, product_idea, ""),
        loop.run_in_executor(None, market_agent, product_idea, ""),
    )
    print(f"   ✅ Round 1 done ({time.time()-start:.1f}s)")

    # Round 2: Stories + Risk (both need Round 1 outputs as context)
    print("Round 2: Groq Stories + Groq Risk running simultaneously...")
    t2 = time.time()
    stories_result, risk_result = await asyncio.gather(
        loop.run_in_executor(None, stories_agent, product_idea, prd_result),
        loop.run_in_executor(None, risk_agent,    product_idea, market_result),
    )
    print(f"   ✅ Round 2 done ({time.time()-t2:.1f}s)")

    print(f"\n✅ Total: {time.time()-start:.1f}s")
    return {"prd": prd_result, "market": market_result,
            "stories": stories_result, "risks": risk_result}

outputs_parallel = asyncio.run(generate_parallel(PRODUCT_IDEA))

"""## Section 9: Conversational Refinement

"""

def chat_session(product_idea: str, outputs: dict):
    """Interactive refinement loop with agent routing."""
    from IPython.display import Markdown, display
    history = []
    print("\n💬 Chat Mode — type 'quit' to exit, 'show prd/market/stories/risks' to display\n")
    while True:
        user_input = input("You: ").strip()
        if not user_input: continue
        if user_input.lower() == "quit": break
        for cmd, key in [("show prd","prd"),("show market","market"),
                         ("show stories","stories"),("show risks","risks")]:
            if user_input.lower() == cmd:
                display(Markdown(outputs.get(key, "Not generated."))); break
        else:
            response, agent = route_refinement(user_input, product_idea, outputs, history)
            print(f"[{agent}]"); display(Markdown(response)); print()
            history += [{"role":"user","content":user_input},
                        {"role":"assistant","content":response}]

# chat_session(PRODUCT_IDEA, outputs)
print("✅ Defined — uncomment last line to run")

"""## Section 10: Export Outputs

"""

def export_outputs(product_idea, outputs, folder="pm_outputs"):
    Path(folder).mkdir(exist_ok=True)
    for fname, key in [("PRD.md","prd"),("Market_Analysis.md","market"),
                       ("User_Stories.md","stories"),("Risk_Assessment.md","risks")]:
        path = Path(folder) / fname
        path.write_text(f"# {fname.replace('.md','').replace('_',' ')}\n**Product:** {product_idea}\n\n---\n\n{outputs.get(key,'')}")
        print(f"✅ {folder}/{fname}")
    (Path(folder)/"pm_suite.json").write_text(json.dumps({
        "product_idea": product_idea,
        "generated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "outputs": outputs}, indent=2))
    print(f"✅ {folder}/pm_suite.json")

export_outputs(PRODUCT_IDEA, outputs)

# Download in Colab
try:
    from google.colab import files
    for f in Path("pm_outputs").iterdir():
        files.download(str(f))
except ImportError:
    print("Files saved to ./pm_outputs/")

"""## Section 11: Launch Streamlit App from Colab

Upload `app.py` first (Files panel → Upload), then run:

"""

!npm install -g localtunnel 2>/dev/null | tail -1
print("✅ localtunnel ready")

import subprocess, threading, time

def run_streamlit():
    subprocess.run([
        "streamlit", "run", "app.py",
        "--server.port", "8501",
        "--server.headless", "true",
        "--server.enableCORS", "false",
        "--server.enableXsrfProtection", "false",
    ])

threading.Thread(target=run_streamlit, daemon=True).start()

# Wait longer for Streamlit to fully start
time.sleep(15)
print("✅ Streamlit running on port 8501")

proc = subprocess.Popen(["lt", "--port", "8501"], stdout=subprocess.PIPE)
time.sleep(5)
url = proc.stdout.readline().decode().strip()
print(f"\n🌐 Public URL: {url}")
print("Open the URL above — click 'Continue' if prompted by localtunnel.")

"""## Summary

### Tech Stack
| Layer | Technology | Cost |
|-------|-----------|------|
| Orchestration | LangChain + `langchain-core` | Free |
| PRD Agent | GPT-4o (OpenAI) | Paid (~$0.01–0.05/run) |
| Stories + Risk Agent | Llama-3.3-70b (Groq) | **Free** |
| Market Agent | Gemini 1.5 Flash (Google) | **Free tier** |
| UI | Streamlit | Free |
| Async execution | asyncio + nest_asyncio | Free |

### Key Concepts Demonstrated
- Multi-LLM orchestration with task-based routing
- LangChain `langchain_core` message interface (modern API)
- Sequential and parallel agent pipelines
- Conversational memory across multi-turn refinements
- Streamlit interactive UI with session state management

"""